version: '3'
services:
  nsqlookupd:
    image: nsqio/nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"
  nsqd:
    image: nsqio/nsqd
    ports:
      - "4150:4150"
      - "4151:4151"
    links:
      - nsqlookupd:nsqlookupd
    command: -lookupd-tcp-address=nsqlookupd:4160
  nsqadmin:
    image: nsqio/nsqadmin
    ports:
      - "4171:4171"
    links:
      - nsqlookupd:nsqlookupd
    command: -lookupd-http-address=nsqlookupd:4161
  vault:
    image: vault
    ports:
      - "9000:9000"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:9000
  dockfiy:
    image: dockify
    ports:
      - "8080:8080"
    environment:
      - TOKEN=root
      - VAULT_ADDR=http://localhost:9000
